fix: Suppress object warning
* ERROR in src/app/routes/simulations/components/metrics.component.ts(31,20): error TS2339: Property 'changeData' does not exist on type 'object'.